version: "3.7"
services:
  product:
    restart: always
    container_name: product
    image: adityazxzxz/product-service:1.0.0
    command: npm run serve
    networks:
      - my_network
    ports:
      - 3030:3000
    environment:
      DATABASE_URL: "postgres://root:root@postgres:5432/my_project"
      DB_HOST: postgres
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: my_project
      DB_PORT: 5432
      APP_HOST: 0.0.0.0
      APP_PORT: 3000
    depends_on:
      - postgres
  postgres:
    restart: always
    container_name: postgres
    image: postgres
    networks:
      - my_network
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_project
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    networks:
      - my_network
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
networks:
  my_network:
    name: my_network
